In [29]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:/Users/pauli/Downloads/Datos/base_datos_2008.csv", nrows = 100000)

In [30]:
df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [3]:
np.corrcoef(df["ArrDelay"],df["DepDelay"])
# muestra la correlación entre las columnas especificadas. El resultado es una matriz con valores nulos dado que el df
# hay datos faltantes, que deben ser imputados o eliminados antes de realizar el cálculo.

array([[nan, nan],
       [nan, nan]])

In [4]:
df.dropna(inplace = True, subset=["ArrDelay","DepDelay"])
# Elimina valores faltantes de las columnas especificadas.

In [5]:
np.corrcoef(df["ArrDelay"],df["DepDelay"])
# ahora ejecutamos la formula de correlación y nos da una matriz de correlaciones.

array([[1.       , 0.9422735],
       [0.9422735, 1.       ]])

In [6]:
np.corrcoef([df["ArrDelay"],df["DepDelay"],df["DepTime"]])

array([[1.        , 0.9422735 , 0.23241529],
       [0.9422735 , 1.        , 0.25725889],
       [0.23241529, 0.25725889, 1.        ]])

In [7]:
df.drop(inplace=True, columns = ["Year", "Cancelled", "Diverted", "Month"])
# Elimonar columnas que no son numéricas o variables dummy

In [8]:
df.corr()
# muestra matriz de correlaciones

DayofMonth  DayOfWeek   DepTime  CRSDepTime   ArrTime  \
DayofMonth           1.000000  -0.118851 -0.001168    0.003749 -0.004445   
DayOfWeek           -0.118851   1.000000  0.031111    0.024400  0.021947   
DepTime             -0.001168   0.031111  1.000000    0.985504  0.796903   
CRSDepTime           0.003749   0.024400  0.985504    1.000000  0.795609   
ArrTime             -0.004445   0.021947  0.796903    0.795609  1.000000   
CRSArrTime          -0.001941   0.027785  0.852191    0.862782  0.887002   
FlightNum            0.072588  -0.039560  0.023409    0.023789  0.011193   
ActualElapsedTime    0.004568   0.015945 -0.069542   -0.074644  0.013706   
CRSElapsedTime      -0.006886   0.017744 -0.065937   -0.070060  0.016936   
AirTime              0.000893   0.014324 -0.065054   -0.069232  0.018445   
ArrDelay             0.027501   0.085299  0.232415    0.180684  0.076353   
DepDelay             0.007231   0.098220  0.257259    0.202200  0.091164   
Distance            -0.006686   0.017525 -0.056849   -0.061167  0.024675   
TaxiIn              -0.012618   0.034878  0.029098    0.024048  0.044000   
TaxiOut              0.040429   0.000337 -0.068401   -0.075218 -0.062210   
CarrierDelay        -0.061650   0.031015  0.029925   -0.015536 -0.027949   
WeatherDelay         0.055178   0.008769 -0.018628   -0.057462 -0.033068   
NASDelay             0.111780   0.001660 -0.128269   -0.149643 -0.067516   
SecurityDelay       -0.012357   0.024726 -0.022763   -0.025722 -0.005993   
LateAircraftDelay    0.079725   0.079787  0.229938    0.227241 -0.050018   

                   CRSArrTime  FlightNum  ActualElapsedTime  CRSElapsedTime  \
DayofMonth          -0.001941   0.072588           0.004568       -0.006886   
DayOfWeek            0.027785  -0.039560           0.015945        0.017744   
DepTime              0.852191   0.023409          -0.069542       -0.065937   
CRSDepTime           0.862782   0.023789          -0.074644       -0.070060   
ArrTime              0.887002   0.011193           0.013706        0.016936   
CRSArrTime           1.000000   0.014385           0.025615        0.032250   
FlightNum            0.014385   1.000000           0.024159        0.025279   
ActualElapsedTime    0.025615   0.024159           1.000000        0.983501   
CRSElapsedTime       0.032250   0.025279           0.983501        1.000000   
AirTime              0.030644   0.021619           0.992457        0.989002   
ArrDelay             0.142571  -0.001017          -0.013101       -0.088450   
DepDelay             0.171454   0.002810           0.020641        0.003833   
Distance             0.042641   0.017180           0.963610        0.979863   
TaxiIn               0.042752   0.007277           0.183375        0.134687   
TaxiOut             -0.061937   0.023976           0.167747        0.070776   
CarrierDelay        -0.004882  -0.020801           0.021032        0.047632   
WeatherDelay        -0.049083   0.004887           0.039746        0.016538   
NASDelay            -0.119460   0.002978           0.208190        0.056008   
SecurityDelay       -0.016722  -0.007659           0.014323        0.015098   
LateAircraftDelay    0.171666  -0.002957          -0.076740       -0.039098   

                    AirTime  ArrDelay  DepDelay  Distance    TaxiIn   TaxiOut  \
DayofMonth         0.000893  0.027501  0.007231 -0.006686 -0.012618  0.040429   
DayOfWeek          0.014324  0.085299  0.098220  0.017525  0.034878  0.000337   
DepTime           -0.065054  0.232415  0.257259 -0.056849  0.029098 -0.068401   
CRSDepTime        -0.069232  0.180684  0.202200 -0.061167  0.024048 -0.075218   
ArrTime            0.018445  0.076353  0.091164  0.024675  0.044000 -0.062210   
CRSArrTime         0.030644  0.142571  0.171454  0.042641  0.042752 -0.061937   
FlightNum          0.021619 -0.001017  0.002810  0.017180  0.007277  0.023976   
ActualElapsedTime  0.992457 -0.013101  0.020641  0.963610  0.183375  0.167747   
CRSElapsedTime     0.989002 -0.08

In [32]:
# corr = round(df.corr(),3)
corr=corr.round(2)
# redondear los valores de la matriz de correlaciones a 3 decimales
corr.style.background_gradient()
# aplica una gradiente a la matriz

In [21]:
df = pd.DataFrame([(.21, .32), (.01, .67), (.66, .03), (.21, .18)],
                  columns=['dogs', 'cats'])
df

dogs  cats
0  0.21  0.32
1  0.01  0.67
2  0.66  0.03
3  0.21  0.18

In [31]:
df.round(1)

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0      2008      1           3          4   2003.0        1955   2211.0   
1      2008      1           3          4    754.0         735   1002.0   
2      2008      1           3          4    628.0         620    804.0   
3      2008      1           3          4    926.0         930   1054.0   
4      2008      1           3          4   1829.0        1755   1959.0   
...     ...    ...         ...        ...      ...         ...      ...   
99995  2008      1          25          5   2204.0        1935    106.0   
99996  2008      1          26          6   1933.0        1935   2234.0   
99997  2008      1          27          7   2047.0        1935   2400.0   
99998  2008      1          28          1   1956.0        1935   2308.0   
99999  2008      1          29          2   1938.0        1935   2308.0   

       CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0            2225            WN        335  ...    4.0      8.0          0   
1            1000            WN       3231  ...    5.0     10.0          0   
2             750            WN        448  ...    3.0     17.0          0   
3            1100            WN       1746  ...    3.0      7.0          0   
4            1925            WN       3920  ...    3.0     10.0          0   
...           ...           ...        ...  ...    ...      ...        ...   
99995        2257            XE       7676  ...    4.0     17.0          0   
99996        2257            XE       7676  ...    4.0     16.0          0   
99997        2257            XE       7676  ...    6.0     18.0          0   
99998        2257            XE       7676  ...    5.0     25.0          0   
99999        2257            XE       7676  ...    5.0     41.0          0   

       CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0                   NaN         0           NaN          NaN      NaN   
1                   NaN         0           NaN          NaN      NaN   
2                   NaN         0           NaN          NaN      NaN   
3                   NaN         0           NaN          NaN      NaN   
4                   NaN         0           2.0          0.0      0.0   
...                 ...       ...           ...          ...      ...   
99995               NaN         0           0.0          0.0      0.0   
99996               NaN         0           NaN          NaN      NaN   
99997               NaN         0          23.0          0.0      0.0   
99998               NaN         0           NaN          NaN      NaN   
99999               NaN         0           NaN          NaN      NaN   

       SecurityDelay  LateAircraftDelay  
0                NaN                NaN  
1                NaN                NaN  
2                NaN                NaN  
3                NaN                NaN  
4                0.0               32.0  
...              ...                ...  
99995            0.0              129.0  
99996            NaN                NaN  
99997            0.0               40.0  
99998            NaN                NaN  
99999            NaN                NaN  

[100000 rows x 29 columns]